### ISSUE TITLE
Error using S3 with Digital Ocean space

### ISSUE THREAD

**Issue by AT-Lorlando** [ndianabasi/adonis-responsive-attachment#11]
I'm using the repo https://github.com/rafas/test-attachments with a digital ocean space and the 1.3.1 release, and when i try to upload any image, i got this error:

#### [1658595602786] ERROR (test-attachments/10228 on Chuya-Sekira): E_CANNOT_READ_FILE: Cannot read file from location

```json
err: {
      "type": "CannotReadFileException",
      "message": "E_CANNOT_READ_FILE: Cannot read file from location \"image_upload_tmp\\cl5y5bn9y0001bcxi3h1y3jqi.jpg\"",
      "stack":
          CannotReadFileException: E_CANNOT_READ_FILE: Cannot read file from location "image_upload_tmp\cl5y5bn9y0001bcxi3h1y3jqi.jpg"
              at Function.invoke (D:\Sandbox\test-attachments\node_modules\@adonisjs\drive\build\src\Exceptions\index.js:30:23)
              [...]
              at UploadsController.store (D:\Sandbox\test-attachments\app\Controllers\Http\UploadsController.ts:22:5)
      "location": "image_upload_tmp\\cl5y5bn9y0001bcxi3h1y3jqi.jpg",
      "original": {
        "type": "NoSuchKey",
        "message": "UnknownError",
        "stack":
            NoSuchKey: UnknownError
                at deserializeAws_restXmlNoSuchKeyResponse (D:\Sandbox\test-attachments\node_modules\@aws-sdk\client-s3\dist-cjs\protocols\Aws_restXml.js:8595:23)
                [...]
                at S3Driver.get (D:\Sandbox\test-attachments\node_modules\@adonisjs\drive-s3\build\src\Drivers\S3.js:114:44)
        "name": "NoSuchKey",
        "$fault": "client",
        "$metadata": {
          "httpStatusCode": 404,
          "attempts": 1,
          "totalRetryDelay": 0
        },
        "Code": "NoSuchKey",
        "BucketName": "altab",
        "RequestId": "tx000000000000058b7198e-0062dc2b51-5242291f-fra1b",
        "HostId": "5242291f-fra1b-fra1-zg02"
      }
    }
```

It's different from the previous error, the location was
`      "location": "image_upload_tmp/image_upload_tmp/cl3p71qps0001dgy8ezl0esv4.png",`
and now
`      "location": "image_upload_tmp\\cl5y4zxm10001w4xi1wrr6674.jpg",`

The file is properly uploaded to the space on DO as you can see here:
```xml
<Contents>
<Key>image_upload_tmp/cl5y5bn9y0001bcxi3h1y3jqi.jpg</Key>
<LastModified>2022-07-23T17:09:37.080Z</LastModified>
<ETag>"adabedb0c7ce028fe5915f088c2d3ac7"</ETag>
<Size>579852</Size>
<StorageClass>STANDARD</StorageClass>
<Owner>
<ID>11535310</ID>
<DisplayName>11535310</DisplayName>
</Owner>
<Type>Normal</Type>
</Contents>
```
The key is different from the location, i don't know if it's normal and if not how can i fix it. 

After some research, i modified the join fonction used to create the path on src/index.js
```js
        this.fileName = attributes.fileName ?? '';
        this.path = attributes.path ?? '';
        this.isLocal = !!this.path || !!this.buffer;
        if (attributes.fileName) {
            // this.relativePath = (0, path_1.join)(exports.tempUploadFolder, attributes.fileName);
            this.relativePath = exports.tempUploadFolder + attributes.fileName;
        }
        else if (attributes.name) {
            this.relativePath = (0, path_1.join)(exports.tempUploadFolder, attributes.name);
        }
```
And it's working properly

**Comment by ndianabasi** [comment]
Thank you for mentioning this.

There seem to be a double slash in the location: `"location": "image_upload_tmp\\cl5y4zxm10001w4xi1wrr6674.jpg"`

I think if it is removed, it might fix the problem.

**Comment by AT-Lorlando** [comment]
I removed it using another 'join' function
```js
if (attributes.fileName) {
            // this.relativePath = (0, path_1.join)(exports.tempUploadFolder, attributes.fileName);
            this.relativePath = exports.tempUploadFolder + attributes.fileName;
        }
```
Do you want make a PR with it ?

**Comment by ndianabasi** [comment]
> Do you want make a PR with it ?

Yes, please.

**Comment by AT-Lorlando** [comment]
Hey again @ndianabasi ,

It look like the normalize method do not normalize:

Here was the original line
```js
        const originalFileBuffer = this.buffer ?? (await this.getDisk().get(this.relativePath));
```
And with the recent PR, we use the normalize function from path, like that
```js
        const originalFileBuffer = this.buffer ?? (await this.getDisk().get((0, path_1.normalize)(this.relativePath)));
```

Digital Ocean spaces use path with `/` and not `\`, while the normalize function replace thoses `/` by a `\`.
```js
console.log(this.relativePath)
// log: image_upload_tmp\cl6gn9m6t00059gxi8xp2cisq.png
console.log((0, path_1.normalize)(this.relativePath))
// log: image_upload_tmp\cl6gn9m6t00059gxi8xp2cisq.png
console.log(this.relativePath.replace(/\\/g, '/'))
// log: image_upload_tmp/cl6gn9m6t00059gxi8xp2cisq.png
```

When we use normalize function, the Disk.get do not work 

```json
{
"message": "E_CANNOT_READ_FILE: Cannot read file from location \"image_upload_tmp\\cl6gnhjx40003o4xi9un1fhyt.png\""
}
```

It work properly when i'm normalizing my own way. so it look like we must normalize the path on our own, with `.replace(/\\/g, '/')`

What do you think about it ?

**Comment by ndianabasi** [comment]
I will need to review the code and completely eliminate the cause of the double slashes in the first place. It was introduced in one of the PRs I merged recently.

**Comment by ndianabasi** [comment]
Handling normalisation manually isn't the best at times. I think a code review is the best way forward at this time.
