### ISSUE TITLE
Error using local disk and s3 DigitalOcean

### ISSUE THREAD

**Issue by rafas** [ndianabasi/adonis-responsive-attachment#6]
## Package version
adonis-responsive-attachment: ^1.3.0

## Node.js and npm version
v14.17.6

## Sample Code (to reproduce the issue)
Send a POST request with an "image" multipart field using Digital Ocean's S3 settings
The code is the default. Best exemplified in the repository.

**Model (default)**
```js
@responsiveAttachment()
public image: ResponsiveAttachmentContract
```

**Controller (default)**
```js
const requestPost = await request.validate(UploadValidator)
const attachment = await ResponsiveAttachment.fromFile(requestPost.image)
const upload = new Upload()
upload.image = attachment
await upload.save()
```

**.env.example**
```
S3_KEY="HJUS........YC3xyz"
S3_SECRET="xyJNeroqP..............RN4txyz"
S3_BUCKET="mybucketname"
S3_REGION="sfo2"
S3_ENDPOINT="https://sfo2.digitaloceanspaces.com"
```

## BONUS (a sample repo to reproduce the issue)
https://github.com/rafas/test-attachments

## Error description
I'm trying to implement `Responsive Attachment` (RA) with an s3 space Digital Ocean
In my tests with `Attachment Lite` the uploads work normally, however when I use `Responsive Attachment` it returns the error below.

---

### Case 1: `local` disk + `s3` disk
In this case `.env` is setting `DRIVE_DISK=local` while **decorator** is setting to **s3** `@responsiveAttachment({ disk: 's3' })`
The error occurs when the `RA` tries to read from disk `s3` the file that was moved to the temporary folder on the `local` disk (image_upload_tmp).
#### Message
`E_CANNOT_READ_FILE: Cannot read file from location "image_upload_tmp/cl3p7e9420001v1y88qa8613s.png"`
Note: Here the file is in the `local` folder but the RA is trying to access it on `s3` disck

### Case 2: only `s3` disk in all Adonis environment
In this case the `.env` is setting `DRIVE_DISK=s3` for the entire Adonis environment, and the decorator is **inheriting** the environment's `s3` disk.
Here the RA manages to send the file to the temp folder on the `s3` disk, but fails when trying to read it.
#### Message
`E_CANNOT_READ_FILE: Cannot read file from location "image_upload_tmp/image_upload_tmp/cl3p7x6yf000115y8dmzf0pqc.png"`
Note: The file is in the `s3` bucket, but the URL appears to be malformed, doubling the folder name "image_upload_tmp/"

Note: At the end of the report both cases return an exception with a typical s3 response when the file does not exist (`"name": "NoSuchKey"` and `"httpStatusCode": 404`).

### Error Stack
```
E_CANNOT_READ_FILE: Cannot read file from location "image_upload_tmp/image_upload_tmp/cl3p71qps0001dgy8ezl0esv4.png"
    err: {
      "type": "CannotReadFileException",
      "message": "E_CANNOT_READ_FILE: Cannot read file from location \"image_upload_tmp/image_upload_tmp/cl3p71qps0001dgy8ezl0esv4.png\"",
      "stack":
          CannotReadFileException: E_CANNOT_READ_FILE: Cannot read file from location "image_upload_tmp/image_upload_tmp/cl3p71qps0001dgy8ezl0esv4.png"
              at Function.invoke (/Users/rafael/test-attachments/node_modules/@adonisjs/drive/build/src/Exceptions/index.js:30:23)
              at S3Driver.getStream (/Users/rafael/test-attachments/node_modules/@adonisjs/drive-s3/build/src/Drivers/S3.js:125:56)
              at processTicksAndRejections (internal/process/task_queues.js:95:5)
              at S3Driver.get (/Users/rafael/test-attachments/node_modules/@adonisjs/drive-s3/build/src/Drivers/S3.js:114:44)
              at ResponsiveAttachment.enhanceFile (/Users/rafael/test-attachments/node_modules/adonis-responsive-attachment/build/src/Attachment/index.js:185:52)
              at ResponsiveAttachment.save (/Users/rafael/test-attachments/node_modules/adonis-responsive-attachment/build/src/Attachment/index.js:209:35)
              at persistAttachment (/Users/rafael/test-attachments/node_modules/adonis-responsive-attachment/build/src/Attachment/decorator.js:59:32)
              at async Promise.all (index 0)
              at Proxy.saveWithAttachments (/Users/rafael/test-attachments/node_modules/adonis-responsive-attachment/build/src/Attachment/decorator.js:96:5)
              at UploadsController.store (/Users/rafael/test-attachments/app/Controllers/Http/UploadsController.ts:22:5)
      "location": "image_upload_tmp/image_upload_tmp/cl3p71qps0001dgy8ezl0esv4.png",
      "original": {
        "type": "NoSuchKey",
        "message": "UnknownError",
        "stack":
            NoSuchKey: UnknownError
                at deserializeAws_restXmlNoSuchKeyResponse (/Users/rafael/test-attachments/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:8595:23)
                at deserializeAws_restXmlGetObjectCommandError (/Users/rafael/test-attachments/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:6208:25)
                at processTicksAndRejections (internal/process/task_queues.js:95:5)
                at /Users/rafael/test-attachments/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24
                at /Users/rafael/test-attachments/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:11:20
                at StandardRetryStrategy.retry (/Users/rafael/test-attachments/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
                at /Users/rafael/test-attachments/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:56:20
                at /Users/rafael/test-attachments/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22
                at S3Driver.getStream (/Users/rafael/test-attachments/node_modules/@adonisjs/drive-s3/build/src/Drivers/S3.js:121:30)
                at S3Driver.get (/Users/rafael/test-attachments/node_modules/@adonisjs/drive-s3/build/src/Drivers/S3.js:114:44)
        "name": "NoSuchKey",
        "$fault": "client",
        "$metadata": {
          "httpStatusCode": 404,
          "attempts": 1,
          "totalRetryDelay": 0
        },
        "Code": "NoSuchKey",
        "BucketName": "mybucketname",
        "RequestId": "tx000000000000096162b03-0062917aa7-2768dd76-sfo2a",
        "HostId": "2768de76-sfo2a-sfo"
      }
    }
```

**Comment by ebbbang** [comment]
We are facing the same issue. I'll try to get a pull request in.

If anyone else can help with the code or understanding do let us know.

**Comment by AT-Lorlando** [comment]
I'm facing the same issue, is there any update ? Does  #10 fix it ?

@ndianabasi is on the Adonis.js discord, i'll try to contact him
